namespace: kube-system

resources:
  - github.com/kubernetes/autoscaler/vertical-pod-autoscaler/deploy?ref=vertical-pod-autoscaler-0.11.0
  - selfsigned-cert.yaml

patchesStrategicMerge:
  - overlays/vpa-admission-controller-deployment.yaml