namespace: kube-system

resources:
  - github.com/kubernetes/autoscaler/vertical-pod-autoscaler/deploy?ref=vertical-pod-autoscaler/v0.9.2
  - selfsigned-cert.yaml

images:
  - name: k8s.gcr.io/autoscaling/vpa-admission-controller:0.8.1
    newTag: 0.9.2
  - name: k8s.gcr.io/autoscaling/vpa-recommender:0.8.1
    newTag: 0.9.2
  - name: k8s.gcr.io/autoscaling/vpa-updater:0.8.1
    newTag: 0.9.2

patchesJson6902:
  - path: patches/crd-patch.json
    target:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: verticalpodautoscalers.autoscaling.k8s.io
      version: v1beta1

patchesStrategicMerge:
  - overlays/vpa-admission-controller-deployment.yaml